language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update

before_script:
  - mkdir -vp ~/.config/jaggedsoft/
  - mkdir -vp build/logs
  - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/composer-test.json -O composer-test.json
  - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/docs.sh -O docs.sh
  - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/doxy.gen -O doxy.gen
  - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/php-binance-api-test.php -O php-binance-api-test.php
  - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/php-binance-api/gh-travis/phpunit.xml -O phpunit.xml
  - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - travis_retry wget https://github.com/phpfmt-next/fmt/raw/master/bin/fmt.phar -O fmt.phar 
  - travis_retry wget https://codecov.io/bash -O codecov.sh
  - COMPOSER=composer-test.json composer -vvv install --no-interaction --no-suggest
  - chmod -v +x codecov.sh
  - chmod -v +x docs.sh
  - chmod -v +x coveralls.phar

script:
  - ./vendor/bin/phpunit --verbose --debug --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php php-binance-api-test
  - php fmt.phar -v --psr2 --indent_with_space=4 -o=php-binance-api.php.fmt php-binance-api.php
  - diff php-binance-api.php.fmt php-binance-api.php

after_success:
    - if [[ $TRAVIS_OS_NAME != "linux" && ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then travis_retry php coveralls.phar -v; fi
    - if [[ $TRAVIS_OS_NAME != "linux" && ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then travis_retry bash -x ./codecov.sh -f "!$TRAVIS_BUILD_DIR/php-binance-api-test.php"; fi
    - if [[ $TRAVIS_OS_NAME != "linux" && ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then travis_retry bash -x ./docs.sh; fi

branches:
  only: master

env:
  global:
    - GH_REPO_NAME: php-binance-api
    - DOXYFILE: $TRAVIS_BUILD_DIR/doxy.gen
    - GH_REPO_REF: github.com/jaggedsoft/php-binance-api.git
    - DOXY_FILES: $TRAVIS_BUILD_DIR/php-binance-api.php
    - DOXY_FILES_EXCLUDE: $TRAVIS_BUILD_DIR/examples/*

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
