language: php

php:
  - 7.0
  
before_script:
  - bash prep.sh

script:
  - bash run.sh

after_success:
 - travis_retry php coveralls.phar -v
 - bash <(curl -s https://codecov.io/bash)

branches:
  only: master
  
cache:
  directories:
  - vendor
  - $HOME/.cache/composer
